# Generated by Django 5.1 on 2025-01-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0003_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lense',
            name='shape',
            field=models.CharField(choices=[('aviator', 'Aviator'), ('square', 'Square'), ('oval', 'Oval'), ('rectangle', 'Rectangle'), ('round', 'Round'), ('geometric', 'Geometric')], default='round', max_length=20),
        ),
    ]
